### ISSUE TITLE
Brute Force Simple Model Sharing

### ISSUE THREAD

**Issue by gfleetwood** [JonathanChiang/TidyShell#1]
Hey Jonathan,

This is the example I was working on. The matrix multiplication problem in R was a simple mistake. I'm using reticulate::source_python here, but switching to the repl shouldn't be too hard.

```
# model_conversion.py

import json 
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression

def predict_from_params(df, params, model = "lin_reg"):
    
    model_dict = {
    "lin_reg": lambda x, y: np.matmul(np.hstack((np.ones((x.shape[0], 1)), 
                                                          x.values)), y.weights.values)
                 }
    
    result = model_dict[model](df, params)
    
    return(result)
    
def main():
    
    df = pd.read_csv("https://bit.ly/2ow0oJO")
    mdl = LinearRegression()

    mdl.fit(df.iloc[:, [0,1,2]], df.iloc[:,[3]])
    
    # use https://github.com/tritemio/pybroom instead?
    df_params = pd.DataFrame(np.concatenate((mdl.intercept_, mdl.coef_[0])), 
                                              columns = ['weights'])
    df_params["columns"] = ['intercept'] + list(df.iloc[:, [0,1,2]].columns)
    df_params = df_params.iloc[:, [1, 0]]
    
    #print(predict_from_params(df.iloc[0:2, [0,1,2]], df_params))
    #print(mdl.predict(df.iloc[0:2, [0,1,2]]))
    
    return(df_params)

if __name__=="__main__":
    main()
```

```
library(tidyverse)
library(reticulate)

reticulate::source_python("mdl_conversion.py")

mdl_params <- main()

iris_mat <- iris[1:2,1:3] %>% 
  add_column(intercept_col = 1, .before = 1) %>% 
  as.matrix()

# mdl_params[,-1] removes the column of feature names
preds <- iris_mat %*% as.matrix(mdl_params[,-1])
```

**Comment by JonathanChiang** [comment]
I like your way better with source_python. REPL would be nice for terminal, but this way is better for reproducibility

**Comment by JonathanChiang** [comment]
Feel free to push this code in a folder too.

**Comment by gfleetwood** [comment]
Will do. The freedom to write the Python side of the code on the fly is truer to the notebook ethos, though. It's tricky.

**Comment by JonathanChiang** [comment]
curious if you tried using an R kernel in jupyter notebook? might be worth it to experiment if you prefer the notebook style.

**Comment by gfleetwood** [comment]
I tried it a while back and didn't like it compared to the RStudio experience. So I'm not wedded to the notebook style as such. Just thought it would be more...flexible.

**Comment by JonathanChiang** [comment]
In terms of IDE experience in Rstudio, it's pretty great.

My only two issues with Rstudio currently is the is saving projects/sessions when there is a lot of in-memory, and managing git could be a little cleaner.

Otherwise Rstudio has the best R experience I'm aware of.

**Comment by gfleetwood** [comment]
I pushed some code to the repo.
