### ISSUE TITLE
tidy shell initial steps 

### ISSUE THREAD

**Issue by gfleetwood** [JonathanChiang/TidyShell#4]
Milestones for tidy shell MVP:

* Script to transform images (MNIST initially) into data of the form for inference by PyTorch model.

* Minimal IDE built on Electron with a radian backend

* Use the IDE to read in the aforementioned data and make predictions in R using a saved (MNIST) PyTorch model.

**Comment by JonathanChiang** [comment]
**Additional Notes**
 - Probably think about serializing work with ONNX (may not be as stable in R)

**Comment by gfleetwood** [comment]
So I finally made some progress, but I'm going to start off with what I didn't manage to do.

* The cmd script for getting data ready for pytorch is easy and hard. Easy if you're using something like MNIST which is in torch's datasets and the class is fully [visible](https://github.com/pytorch/vision/blob/master/torchvision/datasets/mnist.py). It's more complicated when you have to do it from [scratch](https://pytorch.org/tutorials/beginner/data_loading_tutorial.html). Since we're focusing on MNIST up front I say put this on the back burner.

* I retrained the MNIST model and exported it as both a pytorch and an onnx object. I figured out how to reshape data to make predictions from the Udacity course, but I only did it on the saved pytorch model. Lastly I moved all the code over to radian where i created the model object and data in Python and then used reticulate to make predictions in R. It was really straight forward except for one minor complication.

All the stuff I did is in the new torch folder. Next up I going to dive into the minimal radian IDE. I might use this [library](https://github.com/ChrisKnott/Eel) first as it has some nice Python syntactic sugar on top of Electron.

**Comment by JonathanChiang** [comment]
Looks good so far, I need to run through it more closely, later this week. That's awesome you got onnx and pytorch object and were able to use the model in R. Makes me confident we can utilize pieces of apache arrow for ml serialization of object.  

Small tip: you could clean up parts of the repo on push. Like gitignore some of the checkpoints and pycache.

**Comment by gfleetwood** [comment]
Will do.
